
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador_compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 42;
  public static final int SHORT = 15;
  public static final int CONST = 5;
  public static final int CHAR = 4;
  public static final int OCTAL = 52;
  public static final int ENTERO = 50;
  public static final int HEXA = 56;
  public static final int MENOIG = 45;
  public static final int CASE = 3;
  public static final int IGIG = 46;
  public static final int CONTINUE = 6;
  public static final int INT = 12;
  public static final int FOR = 10;
  public static final int WRITE = 20;
  public static final int IDENTIFICADOR = 49;
  public static final int AND = 47;
  public static final int NOT = 30;
  public static final int CARACTER = 55;
  public static final int MENO = 33;
  public static final int OR = 38;
  public static final int DIV = 21;
  public static final int LLAI = 24;
  public static final int MASIG = 43;
  public static final int IG = 34;
  public static final int IF = 11;
  public static final int MULIG = 37;
  public static final int LLAD = 25;
  public static final int DECIMAL = 51;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int MUL = 22;
  public static final int CIENTIFICO = 54;
  public static final int DIF = 41;
  public static final int MOD = 35;
  public static final int BREAK = 2;
  public static final int VOID = 17;
  public static final int MENMEN = 39;
  public static final int MENIG = 48;
  public static final int PCOMA = 28;
  public static final int SWITCH = 16;
  public static final int ELSE = 9;
  public static final int MAYIG = 44;
  public static final int MEN = 23;
  public static final int READ = 19;
  public static final int WHILE = 18;
  public static final int DEFAULT = 7;
  public static final int PARI = 26;
  public static final int DIVIG = 36;
  public static final int PARD = 27;
  public static final int LONG = 13;
  public static final int STRING = 53;
  public static final int MAY = 32;
  public static final int CARACTERN = 57;
  public static final int DP = 29;
  public static final int DO = 8;
  public static final int MAS = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "CASE",
  "CHAR",
  "CONST",
  "CONTINUE",
  "DEFAULT",
  "DO",
  "ELSE",
  "FOR",
  "IF",
  "INT",
  "LONG",
  "RETURN",
  "SHORT",
  "SWITCH",
  "VOID",
  "WHILE",
  "READ",
  "WRITE",
  "DIV",
  "MUL",
  "MEN",
  "LLAI",
  "LLAD",
  "PARI",
  "PARD",
  "PCOMA",
  "DP",
  "NOT",
  "MAS",
  "MAY",
  "MENO",
  "IG",
  "MOD",
  "DIVIG",
  "MULIG",
  "OR",
  "MENMEN",
  "COMA",
  "DIF",
  "MASMAS",
  "MASIG",
  "MAYIG",
  "MENOIG",
  "IGIG",
  "AND",
  "MENIG",
  "IDENTIFICADOR",
  "ENTERO",
  "DECIMAL",
  "OCTAL",
  "STRING",
  "CIENTIFICO",
  "CARACTER",
  "HEXA",
  "CARACTERN"
  };
}

